WIP: Implement tests using Espresso.
This is enough to get "gradlew connectedAndroidTest" to run, but the
actual test crashes with:

    java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
            at uk.org.ngo.squeezer.util.ImageCache.<clinit>(ImageCache.java:80)

This still needs to be resolved.